<?php

namespace TechCorp\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Util\Debug;
/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends EntityRepository
{
/*
	// Requetes DQL
	public function getStatusesAndUsers()
	{
		return $this->_em->createQuery('
			SELECT s, u
			FROM TechCorpFrontBundle:Status s
			JOIN s.user u
			ORDER BY s.createdAt DESC AND 
					s.id DESC
			');
	}


	// Equivalent en QueryBuilder
	public function getStatusesAndUsers()
	{
		return $this->_em->createQueryBuilder()
			->select('s', 'u')
			->from('TechCorpFrontBundle:Status', 's') 
			->join('s.user', 'u') 
			->orderBy('s.createdAt', 'DESC')
			->getQuery() 
			;
	}
*/


	public function getStatusesAndUsers($deleted)
	{
		return $this->_em->createQuery("
			SELECT s, u
			FROM TechCorpFrontBundle:Status s
			JOIN s.user u
			WHERE s.deleted = :deleted
			ORDER BY 
				s.createdAt DESC,
				s.id DESC
			")

			->setParameter('deleted', $deleted);
	}



	public function getUserTimeline($user)
	{
		return $this->_em->createQuery('
			SELECT s, c, u
			FROM TechCorpFrontBundle:Status s
			LEFT JOIN s.comments c
			LEFT JOIN c.user u
			WHERE 
				s.user = :user AND
				s.deleted = false
			ORDER BY 
				s.createdAt DESC
			')

		->setParameter('user', $user);
	}



	public function getFriendsTimeline($user)
	{
		return $this->_em->createQuery
		('
			SELECT s, c, u
			FROM TechCorpFrontBundle:Status s
			LEFT JOIN s.comments c
			LEFT JOIN c.user u
			WHERE 
				s.user in (
					SELECT friends FROM TechCorpFrontBundle:User uf
					JOIN uf.friends friends
					WHERE uf = :user
					)
			ORDER BY 
				s.createdAt DESC
		')

		->setParameter('user', $user);
	}



}
